Make subscribe functions
slayermass/stateForm pull request #42
Opened 2024-10-21 03:21 UTC by DimaKhalimanov

2024-10-22 03:39 UTC, slayermass requested changes

2024-10-22 03:39 UTC, slayermass commented on src/utils/stateForm/index.ts
> +  const subscribe = useCallback<StateFormSubscribeType<FormValues>>(
предлагаю название subscribeOnChanges типа такого. чтоб понятнее было сразу

2024-10-22 03:39 UTC, slayermass commented on src/utils/stateForm/index.ts
> +          const unsubscribeFns = fieldNames.map((fieldName) =>
unsubscribeFns может заинлайнить?

2024-10-22 03:41 UTC, DimaKhalimanov commented on src/utils/stateForm/index.ts
> +  const subscribe = useCallback<StateFormSubscribeType<FormValues>>(
> предлагаю название subscribeOnChanges типа такого. чтоб понятнее было сразу

у subscribe методы есть on и onError. Предлагаю тогда on заменить на onChange

2024-10-22 03:57 UTC, DimaKhalimanov commented on src/utils/stateForm/index.ts
> +          const unsubscribeFns = fieldNames.map((fieldName) =>
Не получится. Она в функции используется.
`return () => unsubscribeFns.forEach((fn) => fn());`

2024-10-22 04:45 UTC, slayermass submitted a review, later dismissed

2024-11-12 09:11 UTC, slayermass approved these changes

2024-11-12 09:11 UTC, merged